version: "3.8"

services:
  # custom image
  app:
    build:
      args:
        user: gabriel
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: laravel-app
    working_dir: /var/www/
    volumes:
      - ./:/var/www/
    restart: unless-stopped
    depends_on:
      - redis
      - queue
    networks:
      - docker-laravel

  #nginx
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 8989:89

    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - docker-laravel

  # db
  mysql:
    image: mysql:5.7.22
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - docker-laravel

  # phpmyadmin
  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - 8383:81
    environment:
      - PMA_ARBITRARY=1
        - PMA_HOST=mysql
        - PMA_PORT=3306
        - PMA_USER=${DB_USERNAME}
        - PMA_PASSWORD=${DB_PASSWORD}
        - PMA_DATABASE=${DB_DATABASE}
    networks:
        - docker-laravel
    volumes:
        - ./docker/phpmyadmin/:/etc/phpmyadmin/

  # redis
  redis:
    image: redis:latest
    networks:
      - docker-laravel

  # queue
  queue:
    build:
      args:
        user: gabriel
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    command: "php artisan queue:work"
    volumes:
      - ./:/var/www
    depends_on:
      - redis
    networks:
      - docker-laravel

networks:
  docker-laravel:
    driver: bridge
